version: "3.8"
services:
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - default
      - elt-jobs_caf9cb_airflow
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

networks:
  elt-jobs_caf9cb_airflow:
    external: true

volumes:
  minio-data:
