name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Code to GCP VM via RSYNC
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "."
          target: "~/developer-trends-elt"
          rm: false

      - name: Inject Credentials
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            mkdir -p ~/developer-trends-elt
            cd ~/developer-trends-elt

            cat << 'EOF' > credentials.json
            ${{ secrets.GCP_CREDENTIALS }}
            EOF
            chmod 600 credentials.json
            docker compose down
            docker compose up -d --build

